// Atomic write of monkey.config.json + .env.local.
//
// Edge case from V1 walk Q6: if init is interrupted between writing config
// and env.local, partial state. Mitigation: write both .tmp files first,
// then rename in sequence. If the second rename fails, log + leave first
// in place; user re-runs init which catches "config already exists".

import { writeFile, rename, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import type { MonkeyConfig } from './schema.js';

export interface EnvLocal {
  BROWSERBASE_API_KEY: string;
  BROWSERBASE_PROJECT_ID: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY?: string;
  TEST_EMAIL?: string;
  TEST_PASSWORD?: string;
}

function formatEnvLocal(env: EnvLocal): string {
  const lines: string[] = ['# Generated by monkey init. Gitignored.', ''];
  for (const [k, v] of Object.entries(env)) {
    if (v === undefined || v === '') continue;
    // Quote values containing spaces or special chars
    const needsQuoting = /[\s"'\\$`]/.test(v);
    lines.push(needsQuoting ? `${k}="${v.replace(/"/g, '\\"')}"` : `${k}=${v}`);
  }
  return lines.join('\n') + '\n';
}

export async function saveConfigAndEnv(opts: {
  dir: string;
  config: MonkeyConfig;
  env: EnvLocal;
}): Promise<void> {
  const cfgPath = join(opts.dir, 'monkey.config.json');
  const envPath = join(opts.dir, '.env.local');
  const cfgTmp = `${cfgPath}.tmp`;
  const envTmp = `${envPath}.tmp`;

  // Write both .tmp files first; abort the operation cleanly if either fails.
  await writeFile(cfgTmp, JSON.stringify(opts.config, null, 2) + '\n');
  try {
    await writeFile(envTmp, formatEnvLocal(opts.env));
  } catch (err) {
    await unlink(cfgTmp).catch(() => {});
    throw err;
  }

  // Rename in sequence: config first, then env.
  try {
    await rename(cfgTmp, cfgPath);
  } catch (err) {
    await unlink(cfgTmp).catch(() => {});
    await unlink(envTmp).catch(() => {});
    throw err;
  }
  try {
    await rename(envTmp, envPath);
  } catch (err) {
    process.stderr.write(
      `\n✗ init partial: monkey.config.json written, .env.local failed.\n` +
        `  Remove ${envTmp} if present, then re-run \`monkey init\`.\n`,
    );
    throw err;
  }
}

export async function saveConfigOnly(dir: string, config: MonkeyConfig): Promise<void> {
  const cfgPath = join(dir, 'monkey.config.json');
  const cfgTmp = `${cfgPath}.tmp`;
  await writeFile(cfgTmp, JSON.stringify(config, null, 2) + '\n');
  await rename(cfgTmp, cfgPath);
}

export async function saveEnvOnly(dir: string, env: EnvLocal): Promise<void> {
  const envPath = join(dir, '.env.local');
  const envTmp = `${envPath}.tmp`;
  await writeFile(envTmp, formatEnvLocal(env));
  await rename(envTmp, envPath);
}
